# Generated by Django 6.0.3 on 2026-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('batting_style', models.CharField(max_length=100)),
                ('bowling_style', models.CharField(max_length=100)),
                ('playing_role', models.CharField(max_length=100)),
                ('country_id', models.IntegerField()),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
    ]
