# Generated by Django 6.0.3 on 2026-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdiAllRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('batting_avg', models.FloatField()),
                ('bowling_avg', models.FloatField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
            ],
            options={
                'db_table': 'odi_all_round',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdiBatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('span', models.CharField(max_length=20)),
                ('matches', models.IntegerField()),
                ('innings', models.IntegerField()),
                ('not_out', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('high_score', models.IntegerField()),
                ('average', models.FloatField()),
                ('balls_faced', models.IntegerField()),
                ('strike_rate', models.FloatField()),
                ('hundreds', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('ducks', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
            ],
            options={
                'db_table': 'odi_batting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdiBowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('span', models.CharField(max_length=20)),
                ('balls', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('average', models.FloatField()),
                ('economy', models.FloatField()),
                ('strike_rate', models.FloatField()),
            ],
            options={
                'db_table': 'odi_bowling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T20AllRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('batting_avg', models.FloatField()),
                ('bowling_avg', models.FloatField()),
            ],
            options={
                'db_table': 't20_all_round',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T20Batting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('average', models.FloatField()),
                ('strike_rate', models.FloatField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
            ],
            options={
                'db_table': 't20_batting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T20Bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('average', models.FloatField()),
                ('economy', models.FloatField()),
                ('strike_rate', models.FloatField()),
            ],
            options={
                'db_table': 't20_bowling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestBatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('span', models.CharField(max_length=20)),
                ('matches', models.IntegerField()),
                ('innings', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('average', models.FloatField()),
                ('strike_rate', models.FloatField()),
            ],
            options={
                'db_table': 'test_batting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestBowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('average', models.FloatField()),
                ('economy', models.FloatField()),
                ('strike_rate', models.FloatField()),
            ],
            options={
                'db_table': 'test_bowling',
                'managed': False,
            },
        ),
    ]
