# Generated by Django 6.0.3 on 2026-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAllRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('batting_avg', models.FloatField()),
                ('bowling_avg', models.FloatField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
            ],
            options={
                'db_table': 'test_all_round',
                'managed': False,
            },
        ),
    ]
