# Generated by Django 6.0.1 on 2026-03-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_testallround'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='odiallround',
            table='odi_allround',
        ),
        migrations.AlterModelTable(
            name='t20allround',
            table='t20_allround',
        ),
        migrations.AlterModelTable(
            name='testallround',
            table='test_allround',
        ),
    ]
